### ISSUE TITLE
Error: The programmatic API was removed in npm v8.0.0

### ISSUE THREAD

**Issue by zacharytyhacz** [probot/create-probot-app#808] opened 2022-12-28 01:52 UTC
My node version: `v18.1.0`

I am trying to run:

```
npx create-probot-app my-app
```

But I get this error output:

```
/Users/zact/.npm/_npx/ac7da0f8d6e6b5c7/node_modules/npm/index.js:4
  throw new Error('The programmatic API was removed in npm v8.0.0')
  ^

Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/Users/zact/.npm/_npx/ac7da0f8d6e6b5c7/node_modules/npm/index.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/zact/.npm/_npx/ac7da0f8d6e6b5c7/node_modules/create-probot-app/bin/helpers/run-npm.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/zact/.npm/_npx/ac7da0f8d6e6b5c7/node_modules/create-probot-app/bin/create-probot-app.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Node.js v18.1.0
```

**Comment by ahadsheriff** [comment] 2022-12-29 00:02
I am receiving the same error as well. Downgrading to NPM version `7.24.2`, the last supporting version, didn't help either.

**Comment by vonsko** [comment] 2022-12-29 10:49
i see the problem is kinda fresh so I took last working version
simply use `npx create-probot-app@v5.0.9`

**Comment by mnrendra** [comment] 2023-01-01 18:56
Thank you @vonsko it works! Seem need to be solved asap for version 5.0.10 for this issue.

**Comment by Cor4zon** [comment] 2023-01-07 18:40
I also have got that issue

**Comment by emawby** [comment] 2023-01-18 21:11
Same issue using npm 9.2.0 and node 19.4.0

**Comment by andykotov** [comment] 2023-01-28 13:52
How to solve this issue and try your probot?
npm version 8.19.3
node version v18.13.0

**Comment by papaissad** [comment] 2023-03-08 08:17
Any ongoing plan for fixing this issue ?!
I also followed the workaround of `npx create-probot-app@v5.0.9 my-example-app`

**Comment by timneedham** [comment] 2023-04-26 21:55
Polite monthly bump! :blush:

**Comment by sangdth** [comment] 2023-06-06 16:34
Version `5.0.10` was just dependency upgrade, and despite the tests were failed, it got merged! So I think using `5.0.9` still OK for now.

**Comment by ZoneTwelve** [comment] 2023-08-11 07:42
Same

**Comment by hasys** [comment] 2023-08-24 10:17
Issue is till there, had to use `5.0.9`

**Comment by wolfy1339** [comment] 2023-11-19 01:37
This should be resolved in the latest version

**Closed by wolfy1339** 2023-11-19 01:37 UTC
